### ISSUE TITLE
build.sh prereqs: configure: error: libgmp not found or uses a different ABI (including static vs shared) when building mpfr

### ISSUE THREAD

**Issue by retiredfeline** [tkchia/build-ia16#24] opened 2023-04-15 12:35 UTC
This is on openSUSE 15.4. When I run the step ./build.sh prereqs

`checking for __gmpz_init in -lgmp... no
configure: error: libgmp not found or uses a different ABI (including static vs shared).
Please read the INSTALL file -- see "In case of problem".`

When I installed the distro's gmp-devel this error went away. The distro's libgmp is also at 6.1.2. I thought build.sh would be independent of the host's packages? Maybe it's picking up the wrong gmp.h or libgmp during configure? The build of gmp produced an include file and static libraries in prefix-gmp/.

**Comment by tkchia** [comment] 2023-04-15 15:38
Hello @retiredfeline,

Thanks for the report.  I am guessing the error happened while building either `mpfr` or `mpc`?  Can you send me or upload a copy of `build-mpfr/*.log` and `build-mpc/*.log`?  I will try to see if I can figure out what the problem is.

Thank you!

**Comment by retiredfeline** [comment] 2023-04-15 16:38
[build.log](https://github.com/tkchia/build-ia16/files/11239992/build.log)
[config.log](https://github.com/tkchia/build-ia16/files/11239994/config.log)

It was during building mpfr. Above are the two log files left in build-mpfr.

I wonder if anybody has built it on a 64-bit system. Because what's left after building gmp in prefix-gmp are 3 directories: include, lib64, and share. Notice it's lib64 and not lib, as it would be on a 32-bit system. This might explain why the link step didn't find the static libraries libgmp.a and libgmp.la, but instead got the distro's libgmp.so.

I should mention that the next two libraries, mpc and isl, had a similar issue, they would only build if the distro's dev packages were installed.

**Comment by tkchia** [comment] 2023-04-15 16:56
Hello @retiredfeline,

Thanks for the information.  I came up with a hacky way to hopefully work around this:
```
diff --git a/build.sh b/build.sh
index 2b22574..e0fe360 100755
--- a/build.sh
+++ b/build.sh
@@ -252,12 +252,19 @@ if in_list prereqs BUILDLIST; then
   cont_build_log "make $PARALLEL"
   cont_build_log "make $PARALLEL install"
   popd
+  # https://github.com/tkchia/build-ia16/issues/24
+  if [ \! -e "$PREFIX-gmp/lib" ] && [ -e "$PREFIX-gmp/lib64" ]; then
+    ln -s lib64 "$PREFIX-gmp/lib"
+  fi
   pushd build-mpfr
   ../mpfr-3.1.5/configure --prefix="$PREFIX-mpfr" \
     --with-gmp="$PREFIX-gmp" --disable-shared 2>&1 | tee build.log
   cont_build_log "make $PARALLEL"
   cont_build_log "make $PARALLEL install"
   popd
+  if [ \! -e "$PREFIX-mpfr/lib" ] && [ -e "$PREFIX-mpfr/lib64" ]; then
+    ln -s lib64 "$PREFIX-mpfr/lib"
+  fi
   pushd build-mpc
   ../mpc-1.0.3/configure --prefix="$PREFIX-mpc" \
     --with-gmp="$PREFIX-gmp" --with-mpfr="$PREFIX-mpfr" --disable-shared 2>&1 \
@@ -265,12 +272,18 @@ if in_list prereqs BUILDLIST; then
   cont_build_log "make $PARALLEL"
   cont_build_log "make $PARALLEL install"
   popd
+  if [ \! -e "$PREFIX-mpc/lib" ] && [ -e "$PREFIX-mpc/lib64" ]; then
+    ln -s lib64 "$PREFIX-mpc/lib"
+  fi
   pushd build-isl
   ../isl-0.16.1/configure --prefix="$PREFIX-isl" \
     --with-gmp-prefix="$PREFIX-gmp" --disable-shared 2>&1 | tee build.log
   cont_build_log "make $PARALLEL"
   cont_build_log "make $PARALLEL install"
   popd
+  if [ \! -e "$PREFIX-isl/lib" ] && [ -e "$PREFIX-isl/lib64" ]; then
+    ln -s lib64 "$PREFIX-isl/lib"
+  fi
 fi
 
 obsolete_gcc_multilibs_installed () {
```
Please try applying the above patch and see if it solves your problem.  If it does, I will push this as a commit.

Thank you!

**Comment by tkchia** [comment] 2023-04-15 16:58
@retiredfeline : by the way, I do happen to be on a 64-bit system, and on my machine `build.sh` does create `lib/` subdirectories rather than `lib64/`.  openSUSE seems to be doing something weird here.

Thank you!

**Comment by retiredfeline** [comment] 2023-04-15 19:52
Thanks, that worked. I think it's an openSUSE Ubunto difference. It should be interesting to see what happens on other 64-bit distros.

**Comment by tkchia** [comment] 2023-04-15 22:28
@retirefeline : thank you for letting me know.  OK to close this issue?

**Comment by retiredfeline** [comment] 2023-04-15 23:24
Yes, I'm closing it.

**Closed** 2023-04-16 04:18 UTC
Labels: bug, help wanted
